# Generated by Django 5.2.4 on 2025-08-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='libraries.library')),
            ],
        ),
    ]
