# Generated by Django 5.2.4 on 2025-08-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_userpin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='address',
        ),
        migrations.RemoveField(
            model_name='library',
            name='image',
        ),
        migrations.RemoveField(
            model_name='library',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='library',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='library',
            name='library_link',
        ),
        migrations.RemoveField(
            model_name='library',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='library',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='library',
            name='seats_all',
        ),
        migrations.RemoveField(
            model_name='library',
            name='service_text',
        ),
        migrations.RemoveField(
            model_name='library',
            name='title',
        ),
        migrations.RemoveField(
            model_name='library',
            name='worktime',
        ),
        migrations.AddField(
            model_name='library',
            name='lib_code',
            field=models.IntegerField(db_index=True, default='0', unique=True),
            preserve_default=False,
        ),
    ]
