# Generated by Django 5.2.4 on 2025-08-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manager_username_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
